package com.dark.aiagent.module.knowledge.controller;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.dark.aiagent.module.knowledge.entity.KnowledgeTopic;
import com.dark.aiagent.module.knowledge.entity.KnowledgeDocument;
import com.dark.aiagent.module.knowledge.service.KnowledgeTopicService;
import com.dark.aiagent.module.knowledge.service.KnowledgeDocumentService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import java.nio.file.Files;
import java.nio.file.Path;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@Tag(name = "知识库控制台")
@RestController
@RequestMapping("/rest/dark/v1/knowledge")
public class KnowledgeController {

    @Autowired
    private KnowledgeTopicService topicService;

    @Autowired
    private KnowledgeDocumentService documentService;

    @Operation(summary = "获取所有主题")
    @GetMapping("/topics")
    public List<KnowledgeTopic> getTopics() {
        return topicService.list();
    }

    @Operation(summary = "创建主题")
    @PostMapping("/topics")
    public KnowledgeTopic createTopic(@RequestBody KnowledgeTopic topic) {
        if (topic.getId() == null) {
            topic.setId(UUID.randomUUID().toString().replace("-", ""));
        }
        topicService.save(topic);
        return topic;
    }

    @Operation(summary = "更新主题")
    @PutMapping("/topics/{id}")
    public KnowledgeTopic updateTopic(@PathVariable("id") String id, @RequestBody KnowledgeTopic topic) {
        topic.setId(id);
        topicService.updateById(topic);
        return topic;
    }

    @Operation(summary = "删除主题及级联清理文档关联")
    @DeleteMapping("/topics/{id}")
    public void deleteTopic(@PathVariable("id") String id) {
        topicService.removeById(id);
        // 级联清理归属此主题的文档记录（仅删除记录，本地文件和向量库视情况另行处理）
        documentService.remove(new QueryWrapper<KnowledgeDocument>().eq("topic_id", id));
    }

    @Operation(summary = "根据主题获取文档列表")
    @GetMapping("/documents")
    public List<KnowledgeDocument> getDocuments(@RequestParam("topicId") String topicId) {
        return documentService.list(new QueryWrapper<KnowledgeDocument>().eq("topic_id", topicId));
    }

    @Operation(summary = "创建文档记录")
    @PostMapping("/documents")
    public KnowledgeDocument createDocument(@RequestBody KnowledgeDocument document) {
        if (document.getId() == null) {
            document.getId(); // Optional: ID generated by default
        }
        document.setStatus("未入库");
        documentService.save(document);
        return document;
    }

    @Operation(summary = "删除文档及清理磁盘")
    @DeleteMapping("/documents/{id}")
    public void deleteDocument(@PathVariable("id") String id) {
        documentService.deleteDocument(id);
    }

    @Operation(summary = "下发分块策略与入库")
    @PostMapping("/documents/{id}/ingest")
    public Map<String, Object> ingestDocument(@PathVariable("id") String id, @RequestBody Map<String, Object> payload) {
        return documentService.initiateIngest(id, payload);
    }

    @Operation(summary = "预览文档物理文件")
    @GetMapping("/documents/{id}/file")
    public ResponseEntity<Resource> getDocumentFile(@PathVariable("id") String id) {
        Resource resource = documentService.getDocumentResource(id);
        try {
            Path path = resource.getFile().toPath();
            String mimeType = Files.probeContentType(path);
            if (mimeType == null) {
                mimeType = MediaType.APPLICATION_OCTET_STREAM_VALUE;
            }
            return ResponseEntity.ok()
                    .contentType(MediaType.parseMediaType(mimeType))
                    .header(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=\"" + resource.getFilename() + "\"")
                    .body(resource);
        } catch (Exception e) {
            return ResponseEntity.internalServerError().build();
        }
    }
}
