name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # cache: maven

      - name: Generate Direct settings.xml
        # 直接通过 Shell 强行生成纯净的配置，所见即所得
        run: |
          cat <<EOF > absolute-settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>tianyaqpzm</username>
                <password>${{ secrets.MVN_DEPLOY_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Run Tests
        run: mvn -B test -U -s absolute-settings.xml
