name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # cache: maven
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Run Tests
        # 执行命令时，不需要加 -s，它会自动去找刚才生成的配置
        run: mvn -B test
        env:
          # ⚠️ 核心修复：在这里，把真实的值注入到上面定义的环境变量里
          MAVEN_USERNAME: tianyaqpzm
          MAVEN_PASSWORD: ${{ secrets.MVN_DEPLOY_TOKEN }}
